# This workflow will setup Python, run create_perf_json.py, and archive
# perf JSON files.

name: Create perf json

on:
  push:
  pull_request:
  schedule:
    # Tuesdays at 9AM PST
    - cron: '0 16 * * 2'

permissions:
  contents: read

jobs:
  create-perf-json:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout perfmon
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Python 3.x
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: "3.x"

    - name: Run unittests
      working-directory: ./scripts/unittesting
      run: python metric_test.py

    - name: Create perf json files
      working-directory: ./scripts
      run: python create_perf_json.py -v

    - name: Archive perf json files
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
        name: perf-json
        path: scripts/perf
        retention-days: 10
        if-no-files-found: error
