# This workflow will setup Python, run unittests, and execute verify_mapfile.py.

name: Verify mapfile.csv

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verify-mapfile:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/scripts/ci/verify_mapfile

    steps:
    - name: Checkout perfmon
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Set up Python 3.x
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: "3.x"

    - name: Install Python packages
      run: pip install -r requirements.txt

    - name: Run verify_mapfile self tests
      run: python -m unittest

    - name: Validate mapfile.csv
      run: python verify_mapfile.py
